### ISSUE TITLE
Error while runing server.py and client.py 

### ISSUE THREAD

**Issue by aanishatdatakalp** [off99555/python-mmap-ipc#1]
```
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    mm = mmap.mmap(-1, img.size, "ARandomTagName")
TypeError: an integer is required (got type str)
```

**Comment by aanishatdatakalp** [comment]
doesn't work for Linux

**Comment by offchan42** [comment]
Thanks for bug report. Did it work when you change the tag name to an arbitrary int on Linux?

**Comment by aanishatdatakalp** [comment]
> Thanks for bug report. Did it work when you change the tag name to an arbitrary int on Linux?

it doesn't. you have to initialise a file in the ram and pass it. 
check this out https://stackoverflow.com/questions/63553692/how-to-use-memory-mapped-file-in-python-linux

**Comment by offchan42** [comment]
Thanks.
